// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Cart: typeof import('./src/components/cart/index.vue')['default']
    Categories: typeof import('./src/components/goods/categories.vue')['default']
    ChangePwd: typeof import('./src/components/userCenter/changePwd.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    GoodsItem: typeof import('./src/components/goods/goodsItem.vue')['default']
    GoodsList: typeof import('./src/components/goods/goodsList.vue')['default']
    Login: typeof import('./src/components/login.vue')['default']
    MyOrder: typeof import('./src/components/userCenter/myOrder.vue')['default']
    MyPublish: typeof import('./src/components/userCenter/myPublish.vue')['default']
    PublishGoods: typeof import('./src/components/goods/publishGoods.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchGoods: typeof import('./src/components/goods/searchGoods.vue')['default']
    Setting: typeof import('./src/components/userCenter/setting.vue')['default']
    Undefined: typeof import('./src/components/index.vue')['default']
    UserCenter: typeof import('./src/components/userCenter/index.vue')['default']
    VanActionBar: typeof import('vant/es')['ActionBar']
    VanActionBarButton: typeof import('vant/es')['ActionBarButton']
    VanActionBarIcon: typeof import('vant/es')['ActionBarIcon']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanDivider: typeof import('vant/es')['Divider']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanSubmitBar: typeof import('vant/es')['SubmitBar']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
